// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoreoMultifuente3.Data;

#nullable disable

namespace MonitoreoMultifuente3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250917104800_CambiadoPrecioADecimal")]
    partial class CambiadoPrecioADecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bigInt");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("name_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("remember_token_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Cache", b =>
                {
                    b.Property<string>("key_varChar")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("expiration_int")
                        .HasColumnType("int");

                    b.Property<string>("value_mediumtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("key_varChar");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.CacheLocks", b =>
                {
                    b.Property<string>("key_varChar")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("expiration_int")
                        .HasColumnType("int");

                    b.Property<string>("owner_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("key_varChar");

                    b.ToTable("cache_locks", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Escenario", b =>
                {
                    b.Property<int>("id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_int"));

                    b.Property<DateTime>("created_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descripcionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ubicacion_id_int")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_int");

                    b.HasIndex("ubicacion_id_int");

                    b.ToTable("escenarios", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.FailedJobs", b =>
                {
                    b.Property<int>("id_bigInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_bigInt"));

                    b.Property<string>("connection_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("exception_longtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("failed_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payload_longtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("queue_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("uuid_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_bigInt");

                    b.ToTable("failed_jobs", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.JobBatches", b =>
                {
                    b.Property<string>("id_varChar")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("canceled_at_int")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at_int")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("failed_jobs_ids_longtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("failed_jobs_int")
                        .HasColumnType("int");

                    b.Property<int>("finished_at_int")
                        .HasColumnType("int");

                    b.Property<string>("name_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pending_jobs_int")
                        .HasColumnType("int");

                    b.Property<int>("total_jobs_int")
                        .HasColumnType("int");

                    b.HasKey("id_varChar");

                    b.ToTable("job_batches", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Jobs", b =>
                {
                    b.Property<int>("id_bigInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_bigInt"));

                    b.Property<int>("attempts_tinyInt")
                        .HasColumnType("int");

                    b.Property<int>("available_at_int")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at_int")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payload_longtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("queue_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("reserved_at_int")
                        .HasColumnType("int");

                    b.HasKey("id_bigInt");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Medicion", b =>
                {
                    b.Property<int>("registro_medicion_id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("registro_medicion_id_int"));

                    b.Property<DateTime>("created_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by_bigInt")
                        .HasColumnType("int");

                    b.Property<int>("escenarios_escenario_id_int")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_hora_dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("parametros_parametro_id_int")
                        .HasColumnType("int");

                    b.Property<int>("sensores_sensor_id_int")
                        .HasColumnType("int");

                    b.Property<int>("status_enum")
                        .HasColumnType("int");

                    b.Property<int>("users_id_bigInt")
                        .HasColumnType("int");

                    b.Property<double?>("valor_analogico_double")
                        .HasColumnType("double");

                    b.Property<int?>("valor_digital_float")
                        .HasColumnType("int");

                    b.HasKey("registro_medicion_id_int");

                    b.HasIndex("escenarios_escenario_id_int");

                    b.HasIndex("parametros_parametro_id_int");

                    b.HasIndex("sensores_sensor_id_int");

                    b.HasIndex("users_id_bigInt");

                    b.ToTable("mediciones", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.MigrationHistory", b =>
                {
                    b.Property<int>("id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_int"));

                    b.Property<int>("batch_int")
                        .HasColumnType("int");

                    b.Property<string>("migration_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_int");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.PasswordResetTokens", b =>
                {
                    b.Property<string>("email_varChar")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("token_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("email_varChar");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Permissions", b =>
                {
                    b.Property<int>("id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_int"));

                    b.Property<DateTime>("created_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("slug_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_int");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.RolePermission", b =>
                {
                    b.Property<int>("id_bigInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_bigInt"));

                    b.Property<int>("Permissionsid_int")
                        .HasColumnType("int");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("permissions_permission_id_int")
                        .HasColumnType("int");

                    b.Property<int>("roles_rol_id_int")
                        .HasColumnType("int");

                    b.HasKey("id_bigInt");

                    b.HasIndex("Permissionsid_int");

                    b.HasIndex("RolesId");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Sensor", b =>
                {
                    b.Property<int>("sensor_id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("sensor_id_int"));

                    b.Property<string>("modelo_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre_sensor_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precio_decimal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("tipos_int")
                        .HasColumnType("int");

                    b.HasKey("sensor_id_int");

                    b.ToTable("sensores", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Sessions", b =>
                {
                    b.Property<string>("id_varChar")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ip_address_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("last_activity_int")
                        .HasColumnType("int");

                    b.Property<string>("payload_longtext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_agent_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("user_id_bigInt")
                        .HasColumnType("int");

                    b.HasKey("id_varChar");

                    b.HasIndex("user_id_bigInt");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Ubicacion", b =>
                {
                    b.Property<int>("ubicacion_id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ubicacion_id_int"));

                    b.Property<DateTime>("created_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("latitud_decimal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("longitud_decimal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("nombre_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at_timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ubicacion_id_int");

                    b.ToTable("ubicaciones", (string)null);
                });

            modelBuilder.Entity("Parametro", b =>
                {
                    b.Property<int>("parametro_id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("parametro_id_int"));

                    b.Property<string>("nombre_parametro_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sensores_sensor_id_int")
                        .HasColumnType("int");

                    b.Property<string>("unidad_medida_varChar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("parametro_id_int");

                    b.HasIndex("sensores_sensor_id_int");

                    b.ToTable("parametros", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Escenario", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.Ubicacion", "Ubicacion")
                        .WithMany("Escenarios")
                        .HasForeignKey("ubicacion_id_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Medicion", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.Escenario", "Escenario")
                        .WithMany("Mediciones")
                        .HasForeignKey("escenarios_escenario_id_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parametro", "Parametro")
                        .WithMany("Mediciones")
                        .HasForeignKey("parametros_parametro_id_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoMultifuente3.Models.Sensor", "Sensor")
                        .WithMany("Mediciones")
                        .HasForeignKey("sensores_sensor_id_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", "User")
                        .WithMany("Mediciones")
                        .HasForeignKey("users_id_bigInt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escenario");

                    b.Navigation("Parametro");

                    b.Navigation("Sensor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.RolePermission", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.Permissions", "Permissions")
                        .WithMany()
                        .HasForeignKey("Permissionsid_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Permissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Sessions", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("user_id_bigInt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Parametro", b =>
                {
                    b.HasOne("MonitoreoMultifuente3.Models.Sensor", "Sensor")
                        .WithMany("Parametros")
                        .HasForeignKey("sensores_sensor_id_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.ApplicationUser", b =>
                {
                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Escenario", b =>
                {
                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Sensor", b =>
                {
                    b.Navigation("Mediciones");

                    b.Navigation("Parametros");
                });

            modelBuilder.Entity("MonitoreoMultifuente3.Models.Ubicacion", b =>
                {
                    b.Navigation("Escenarios");
                });

            modelBuilder.Entity("Parametro", b =>
                {
                    b.Navigation("Mediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
